name = "1erGTD - French Army Radios for ACRE2"
prefix = "acrefr"
author = "GrueArbre, Starlight"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
files = [
    "mod.cpp"
]
exclude = [
    "*.psd",
    "*.png",
    "*.tga"
]